### ISSUE TITLE
Printing training process suddenly stopped during training

### ISSUE THREAD

**Issue by GitHub-Ju** [zwx8981/LIQE#13]
![image](https://github.com/zwx8981/LIQE/assets/99105298/b58f96f6-0f79-4b70-8f55-8e3a7199a3f9)
During the training process, the printing training process suddenly stopped. What is the reason?

**Comment by zwx8981** [comment]
Not sure, may be similar to https://github.com/zwx8981/LIQE/issues/4#issuecomment-1558441667. Just stop and try it again.

**Comment by GitHub-Ju** [comment]
![image](https://github.com/zwx8981/LIQE/assets/99105298/f167f018-b362-40d5-9adc-718983461e0d)
If pin_memory is set to true, the following error will be reported, so I set it to false. Is it related to this?

**Comment by GitHub-Ju** [comment]
> 不确定，可能类似于 [#4（评论）。](https://github.com/zwx8981/LIQE/issues/4#issuecomment-1558441667)停下来再试一次。
![image](https://github.com/zwx8981/LIQE/assets/99105298/b367458e-54e1-49f8-bc16-65b3b249501b)
If pin_memory is set to true, the following error will be reported, so I set it to false. Is it related to this?

**Comment by zwx8981** [comment]
1. I didn't try setting pin_memory to True. In my case, the training stucking problem occasionally and randomly occurs. Sorry but I think the best pratice to handle this issue would still be retrying.

**Comment by GitHub-Ju** [comment]
> 1. I didn't try setting pin_memory to True. In my case, the training stucking problem occasionally and randomly occurs. Sorry but I think the best pratice to handle this issue would still be retrying.

alright, thank you very much!

**Comment by zwx8981** [comment]
@GitHub-Ju Hi, you may try this. https://github.com/zwx8981/LIQE/issues/17#issuecomment-1891385565
