### ISSUE TITLE
About the test data used in aigc cross model evaluation？

### ISSUE THREAD

**Issue by zht8506** [zwx8981/LIQE#14]
thank you for your excellent work. I'm very interested in your AIGC cross-model validation on github code. I want to know which part of these datasets (such as AGIQA-3k) serves as the test set. Is it the entire data set or a part of it (such as 20%). hope to your reply, thanks.

**Comment by zwx8981** [comment]
@zht8506 Hi, thanks for your interest ! In the cross-dataset setting, all the evaluation are perfomed on the entire datasets.

**Comment by zht8506** [comment]
Thank you for your prompt reply. Have a nice day!

**Comment by zht8506** [comment]
Thank you for your prompt reply. Have a nice day!
