### ISSUE TITLE
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for CLIP: 	Missing key(s) in state_dict: "positional_embedding", "text_projection", "logit_scale", "visual.class_embedding", "visual.positional_embedding", "visual.proj", "visual.conv1.weight", "visual.ln_pre.weight", "visual.ln_pre.bias", "visual.transformer.resblocks.0.attn.in_proj_weight",

### ISSUE THREAD

**Issue by zhang1483** [zwx8981/LIQE#15]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIP:
	Missing key(s) in state_dict: "positional_embedding", "text_projection", "logit_scale", "visual.class_embedding", "visual.positional_embedding", "visual.proj", "visual.conv1.weight", "visual.ln_pre.weight", "visual.ln_pre.bias", "visual.transformer.resblocks.0.attn.in_proj_weight",
训练之后的权重放入demo，会出现模型不匹配的问题是为什么，自己训练的权重参数比作者给的大。

**Comment by zwx8981** [comment]
训练时除了模型权重还会保存优化器状态等，你torch.load之后要用'state_dict'作为key把模型权重提取出来然后再载入模型。

**Comment by routll** [comment]
> 训练时除了模型权重还会保存优化器状态等，你torch.load之后要用'model_state_dict'作为key把模型权重提取出来，然后再载入模型。

谢谢大神！！！解决了！

**Comment by hjb25286** [comment]
> 训练时除了模型权重还会保存优化器状态等，你torch.load之后要用'model_state_dict'作为key把模型权重提取出来然后再载入模型。

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [768, 3, 32, 32], but got 5-dimensional input of size [15, 468, 3, 224, 224] instead
这样修改之后，出现这种错误，请问您有什么解决方法吗

**Comment by zwx8981** [comment]
@hjb25286 这个问题跟model load无关，请提供更详细的描述
