### ISSUE TITLE
An inquiry about the pause during the training process

### ISSUE THREAD

**Issue by ibiii82** [zwx8981/LIQE#17]
I am also experiencing a pause during the training process. It seems to be a similar issue as the questions below. After searching online, it appears that it could be a version-related problem. Could I please receive detailed information about the training environment?

**Comment by zwx8981** [comment]
@ibiii82 Hi, thanks for your endeavor to solve this problem. I used PyTorch 1.8 to train the LIQE with Python 3.8.11 on Ubuntu 20.04.

**Comment by ibiii82** [comment]
Thank you. I tried loading data with the environment you suggested, and it seems to be working fine up to 80 epochs. If any additional errors occur, I will share the issues accordingly.
