### ISSUE TITLE
Which specific weights does `liqe_mix` refer to?

### ISSUE THREAD

**Issue by ZachL1** [zwx8981/LIQE#28]
Thank you for your open-source contribution and great work!

According to the description in the paper, you actually used ten different splits to train the model. So, which split's weights are provided as `liqe_mix` in pyiqa?

**Comment by zwx8981** [comment]
Hi @ZachL1 , sorry for the late reply. It's the first split.

**Comment by ZachL1** [comment]
Thanks for your reply!
