### ISSUE TITLE
liqe_mix

### ISSUE THREAD

**Issue by YaoShunyu19** [zwx8981/LIQE#30]
Hi!
I would like to know if the KonIQ dataset used in the mixed training sets of the LIQE_Mix model is the official training set, or as mentioned in the paper, just a random 70% sample?
Thanks!
```
import pyiqa
model = pyiqa.create_metric('liqe_mix', as_loss=False) #Trained on multiple datasets as in the paper.
score = model(img_path)
```

**Comment by zwx8981** [comment]
Hi, it's not the official split.
