### ISSUE TITLE
测试结果不在[0,1]区间

### ISSUE THREAD

**Issue by baoyu2020** [zwx8981/LIQE#32]
您好！
请问为何测试结果不在[0,1]区间？
相同的输入，使用DBCNN, 结果是0.49859，LIQE是3.3864

######Test LIQE#####
```
import torch
import cv2
import torch.nn.functional as F
import pyiqa

iqa_metric = pyiqa.create_metric("liqe_mix", device="cuda")
img = cv2.imread('/data1/home/Testcodec/bench/jpeg-ai/invcompress/q8/00003_TE_1944x1296.png')
img = torch.tensor(img).permute(2, 0, 1).float()
img = img.unsqueeze(0) / 255.0
print(img.shape)
print(iqa_metric(img))
del img
```

######Out#####
torch.Size([1, 3, 1296, 1944])
tensor([3.3864], device='cuda:0')

![00009_TE_1976x1312_rec](https://github.com/user-attachments/assets/beab6cca-bdbe-481f-b11b-e8aa81fcabf2)

**Comment by zwx8981** [comment]
你好，LIQE的分数区间是[1,5]
