### ISSUE TITLE
The pretrained model is trained on which dataset?

### ISSUE THREAD

**Issue by liuppboy** [zwx8981/LIQE#6]
Hi,  may I ask which dataset do you use for training? Is the score range from 1 to 5? Thanks!

**Comment by zwx8981** [comment]
@liuppboy Hi, thanks for your interest in our work. 

1, Similar to our previous work UNIQUE (TIP2021), the pre-trained model is jointly trained on a combinations of the training sets from six datasets (LIVE, CSIQ, BID, LIVE Challenge, KonIQ-10k, and KADID-10k) under the learning-to-rank framework. 

2, Yes, the score ranges from 1 to 5.
